[tools]
rojo = "rojo-rbx/rojo@7.2.1"
stylua = "Kampfkarren/selene@0.20.0"
selene = "johnnymorganz/stylua@0.14.2"

rbxcloud = "Sleitnick/rbxcloud@0.1.0-alpha.10"
wally = "UpliftGames/wally@0.3.1"
lune = "filiptibell/lune@0.7.11"