[package]
name = "itsjames212/dragon-ball-rb"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
# Knit = "sleitnick/knit@^1.6"
Roact = "roblox/roact@1.4.0"
Component = "sleitnick/component@2.4.7"
Trove = "sleitnick/trove@1.0.1"
Loader = "sleitnick/loader@2.0.0"
Signal = "sleitnick/signal@2.0.1"
Promise = "evaera/promise@^3"